version: '2.1'

services:
  ros-master:
    extends:
      file: ros_master/docker-compose.yml
      service: ros-master

  brain:
    extends:
      file: brain/docker-compose.yml
      service: brain
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=brain"
    depends_on:
      ros-master:
        condition: service_healthy

networks:
  ros:
    driver: bridge
